version: "1"
services:
  kysymyspankki:
    image: jkur00/kysymyspankki
    ports:
      - 4567:4567
    container_name: kysymyspankki
  watchtower:
    image: containerrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower