name: Release Kysymyspankki

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Heroku via docker
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - name: Build, push and release new image to Heroku
      run: |
        heroku container:push web -a kyssaripankki123
        heroku container:release web -a kyssaripankki123