name: Release Kysymyspankki

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Heroku via docker
      run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

    - name: Build, push and release new image to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ secrets.APP_NAME }}
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME